import type { AppData } from "@/lib/types"

export const SEED_APP_DATA: AppData = {
  settings: {
    startingBankroll: 500,
    currency: "USD",
    rules: {
      stopLossAmount: 120,
      withdrawalTriggerAmount: 150,
      withdrawalAmount: 100,
      minBankrollFloor: 250,
    },
  },
  sessions: [
    {
      id: "session-seed-1",
      date: "2026-03-20",
      gameType: "Spins",
      buyIn: 10,
      entries: 12,
      totalInvested: 120,
      cashout: 172,
      profitLoss: 52,
      notes: "Stayed disciplined and quit after a good run.",
      durationMinutes: 95,
      tags: ["played well", "good quit"],
    },
    {
      id: "session-seed-2",
      date: "2026-03-23",
      gameType: "Cash",
      buyIn: 25,
      entries: 2,
      totalInvested: 50,
      cashout: 10,
      profitLoss: -40,
      notes: "Forced a thin value bet at the end.",
      durationMinutes: 80,
      tags: ["tilt", "bad call"],
    },
    {
      id: "session-seed-3",
      date: "2026-03-27",
      gameType: "MTT",
      buyIn: 22,
      entries: 3,
      totalInvested: 66,
      cashout: 215,
      profitLoss: 149,
      notes: "Strong final table decisions.",
      durationMinutes: 190,
      tags: ["played well", "shot take"],
    },
    {
      id: "session-seed-4",
      date: "2026-03-30",
      gameType: "Spins",
      buyIn: 10,
      entries: 10,
      totalInvested: 100,
      cashout: 88,
      profitLoss: -12,
      notes: "Stopped after planned stop-loss threshold.",
      durationMinutes: 70,
      tags: ["good quit"],
    },
  ],
  withdrawals: [
    {
      id: "withdrawal-seed-1",
      date: "2026-03-31",
      amount: 100,
      note: "Secured profit after hitting trigger",
    },
  ],
  deposits: [
    {
      id: "deposit-seed-1",
      date: "2026-03-18",
      amount: 0,
      note: "No additional deposits yet",
    },
  ],
}
