import type { AppData } from "@/lib/types"

export const SEED_APP_DATA: AppData = {
  settings: {
    startingBankroll: 700,
    currency: "USD",
    rules: {
      stopLossAmount: 160,
      withdrawalTriggerAmount: 220,
      withdrawalAmount: 150,
      minBankrollFloor: 450,
    },
  },
  sessions: [
    {
      id: "session-seed-1",
      date: "2026-02-03",
      gameType: "Spins",
      buyIn: 10,
      entries: 12,
      totalInvested: 120,
      cashout: 145,
      profitLoss: 25,
      notes: "Solid volume block, stayed patient after early coolers.",
      durationMinutes: 88,
      tags: ["played well", "good quit"],
    },
    {
      id: "session-seed-2",
      date: "2026-02-05",
      gameType: "Spins",
      buyIn: 10,
      entries: 15,
      totalInvested: 150,
      cashout: 126,
      profitLoss: -24,
      notes: "Chased volume while a bit tired. Stopped before tilt escalated.",
      durationMinutes: 102,
      tags: ["tilt", "good quit"],
    },
    {
      id: "session-seed-3",
      date: "2026-02-08",
      gameType: "Cash",
      buyIn: 100,
      entries: 2,
      totalInvested: 200,
      cashout: 265,
      profitLoss: 65,
      notes: "Good table selection and cleaner river folds.",
      durationMinutes: 146,
      tags: ["played well"],
    },
    {
      id: "session-seed-4",
      date: "2026-02-11",
      gameType: "MTT",
      buyIn: 22,
      entries: 3,
      totalInvested: 66,
      cashout: 0,
      profitLoss: -66,
      notes: "Busted close to the money after two flips lost.",
      durationMinutes: 178,
      tags: ["bad call"],
    },
    {
      id: "session-seed-5",
      date: "2026-02-14",
      gameType: "MTT",
      buyIn: 22,
      entries: 4,
      totalInvested: 88,
      cashout: 340,
      profitLoss: 252,
      notes: "Deep run and final table discipline paid off.",
      durationMinutes: 265,
      tags: ["played well", "shot take"],
    },
    {
      id: "session-seed-6",
      date: "2026-02-18",
      gameType: "Spins",
      buyIn: 10,
      entries: 10,
      totalInvested: 100,
      cashout: 94,
      profitLoss: -6,
      notes: "Slight downswing, closed on schedule.",
      durationMinutes: 72,
      tags: ["good quit"],
    },
    {
      id: "session-seed-7",
      date: "2026-02-21",
      gameType: "Cash",
      buyIn: 100,
      entries: 3,
      totalInvested: 300,
      cashout: 248,
      profitLoss: -52,
      notes: "Overcalled one spot vs a value-heavy line.",
      durationMinutes: 138,
      tags: ["bad call"],
    },
    {
      id: "session-seed-8",
      date: "2026-02-26",
      gameType: "Spins",
      buyIn: 10,
      entries: 18,
      totalInvested: 180,
      cashout: 228,
      profitLoss: 48,
      notes: "Kept focus and avoided unnecessary high-variance lines.",
      durationMinutes: 124,
      tags: ["played well"],
    },
    {
      id: "session-seed-9",
      date: "2026-03-02",
      gameType: "MTT",
      buyIn: 33,
      entries: 3,
      totalInvested: 109,
      cashout: 0,
      profitLoss: -109,
      notes: "No cashes this slate. Bankroll rule held.",
      durationMinutes: 201,
      tags: ["good quit"],
    },
    {
      id: "session-seed-10",
      date: "2026-03-08",
      gameType: "Cash",
      buyIn: 125,
      entries: 2,
      totalInvested: 250,
      cashout: 395,
      profitLoss: 145,
      notes: "Strong value extraction in two deep spots.",
      durationMinutes: 158,
      tags: ["played well"],
    },
    {
      id: "session-seed-11",
      date: "2026-03-15",
      gameType: "Spins",
      buyIn: 10,
      entries: 16,
      totalInvested: 160,
      cashout: 181,
      profitLoss: 21,
      notes: "Small green day, no major leaks.",
      durationMinutes: 99,
      tags: ["played well"],
    },
    {
      id: "session-seed-12",
      date: "2026-03-22",
      gameType: "Other",
      buyIn: 20,
      entries: 4,
      totalInvested: 80,
      cashout: 120,
      profitLoss: 40,
      notes: "Short private game session with controlled risk.",
      durationMinutes: 84,
      tags: ["good quit"],
    },
    {
      id: "session-seed-13",
      date: "2026-03-27",
      gameType: "Spins",
      buyIn: 10,
      entries: 13,
      totalInvested: 130,
      cashout: 102,
      profitLoss: -28,
      notes: "Not my best focus; stepped away early.",
      durationMinutes: 77,
      tags: ["tilt", "good quit"],
    },
    {
      id: "session-seed-14",
      date: "2026-03-31",
      gameType: "Cash",
      buyIn: 110,
      entries: 2,
      totalInvested: 220,
      cashout: 310,
      profitLoss: 90,
      notes: "Closed the month with patient value-heavy lines.",
      durationMinutes: 141,
      tags: ["played well"],
    },
  ],
  withdrawals: [
    {
      id: "withdrawal-seed-1",
      date: "2026-02-15",
      amount: 150,
      note: "Locked in first cycle profit",
    },
    {
      id: "withdrawal-seed-2",
      date: "2026-03-18",
      amount: 300,
      note: "Secured gains after another trigger run",
    },
  ],
  deposits: [
    {
      id: "deposit-seed-1",
      date: "2026-02-01",
      amount: 300,
      note: "Top-up to widen MTT + cash mix",
    },
  ],
}
